import { CityHeatInfo, HourlyForecastItem, VulnerableProfile, AdvisoryItem } from '../types/heat';

export const POPULAR_CITIES: CityHeatInfo[] = [
  {
    id: 'hyderabad',
    name: 'Hyderabad',
    state: 'Telangana',
    lat: 17.3850,
    lon: 78.4867,
    currentTemp: 39,
    feelsLikeTemp: 44,
    humidity: 62,
    windSpeedKmH: 14,
    riskLevel: 'danger',
    verdict: 'Take care during the afternoon.',
    isSafeOutsideNow: false,
    peakDangerWindow: '12:00 PM – 4:00 PM',
    uvIndex: 9,
    updatedAt: 'Just now',
  },
  {
    id: 'delhi',
    name: 'Delhi',
    state: 'Delhi',
    lat: 28.6139,
    lon: 77.2090,
    currentTemp: 41,
    feelsLikeTemp: 45,
    humidity: 48,
    windSpeedKmH: 14,
    riskLevel: 'extreme',
    verdict: 'Dangerous dry heat. Avoid midday outdoor activity.',
    isSafeOutsideNow: false,
    peakDangerWindow: '11:00 AM – 4:30 PM',
    uvIndex: 9,
    updatedAt: 'Just now',
  },
  {
    id: 'mumbai',
    name: 'Mumbai',
    state: 'Maharashtra',
    lat: 19.0760,
    lon: 72.8777,
    currentTemp: 35,
    feelsLikeTemp: 42,
    humidity: 78,
    windSpeedKmH: 16,
    riskLevel: 'danger',
    verdict: 'High humidity is trapping heat. Stay hydrated.',
    isSafeOutsideNow: false,
    peakDangerWindow: '12:00 PM – 4:00 PM',
    uvIndex: 8,
    updatedAt: '5 mins ago',
  },
  {
    id: 'chennai',
    name: 'Chennai',
    state: 'Tamil Nadu',
    lat: 13.0827,
    lon: 80.2707,
    currentTemp: 36,
    feelsLikeTemp: 43,
    humidity: 75,
    windSpeedKmH: 18,
    riskLevel: 'danger',
    verdict: 'Muggy and oppressive heat. Limit sun exposure.',
    isSafeOutsideNow: false,
    peakDangerWindow: '12:00 PM – 3:30 PM',
    uvIndex: 9,
    updatedAt: '8 mins ago',
  },
  {
    id: 'bengaluru',
    name: 'Bengaluru',
    state: 'Karnataka',
    lat: 12.9716,
    lon: 77.5946,
    currentTemp: 28,
    feelsLikeTemp: 29,
    humidity: 55,
    windSpeedKmH: 18,
    riskLevel: 'safe',
    verdict: 'Conditions are relatively comfortable today.',
    isSafeOutsideNow: true,
    peakDangerWindow: 'None',
    uvIndex: 5,
    updatedAt: '10 mins ago',
  },
  {
    id: 'ahmedabad',
    name: 'Ahmedabad',
    state: 'Gujarat',
    lat: 23.0225,
    lon: 72.5714,
    currentTemp: 40,
    feelsLikeTemp: 43,
    humidity: 42,
    windSpeedKmH: 16,
    riskLevel: 'extreme',
    verdict: 'Severe afternoon heat. Postpone non-essential travel.',
    isSafeOutsideNow: false,
    peakDangerWindow: '11:30 AM – 4:00 PM',
    uvIndex: 10,
    updatedAt: '5 mins ago',
  },
  {
    id: 'jaipur',
    name: 'Jaipur',
    state: 'Rajasthan',
    lat: 26.9124,
    lon: 75.7873,
    currentTemp: 39,
    feelsLikeTemp: 41,
    humidity: 32,
    windSpeedKmH: 15,
    riskLevel: 'danger',
    verdict: 'Intense dry sun. Cover your head and stay in the shade.',
    isSafeOutsideNow: false,
    peakDangerWindow: '11:30 AM – 4:30 PM',
    uvIndex: 10,
    updatedAt: '15 mins ago',
  },
  {
    id: 'kolkata',
    name: 'Kolkata',
    state: 'West Bengal',
    lat: 22.5726,
    lon: 88.3639,
    currentTemp: 35,
    feelsLikeTemp: 42,
    humidity: 75,
    windSpeedKmH: 11,
    riskLevel: 'danger',
    verdict: 'Very high humidity with elevated heat. Rest frequently.',
    isSafeOutsideNow: false,
    peakDangerWindow: '11:30 AM – 3:30 PM',
    uvIndex: 8,
    updatedAt: '20 mins ago',
  },
  {
    id: 'bhubaneswar',
    name: 'Bhubaneswar',
    state: 'Odisha',
    lat: 20.2961,
    lon: 85.8245,
    currentTemp: 38,
    feelsLikeTemp: 45,
    humidity: 70,
    windSpeedKmH: 13,
    riskLevel: 'extreme',
    verdict: 'Heavy humid heat stress. Avoid strenuous outdoor work.',
    isSafeOutsideNow: false,
    peakDangerWindow: '11:00 AM – 4:00 PM',
    uvIndex: 9,
    updatedAt: '12 mins ago',
  },
  {
    id: 'nagpur',
    name: 'Nagpur',
    state: 'Maharashtra',
    lat: 21.1458,
    lon: 79.0882,
    currentTemp: 42,
    feelsLikeTemp: 46,
    humidity: 35,
    windSpeedKmH: 12,
    riskLevel: 'extreme',
    verdict: 'Severe heatwave conditions. Stay in cooled spaces.',
    isSafeOutsideNow: false,
    peakDangerWindow: '11:00 AM – 5:00 PM',
    uvIndex: 11,
    updatedAt: '12 mins ago',
  },
  {
    id: 'vijayawada',
    name: 'Vijayawada',
    state: 'Andhra Pradesh',
    lat: 16.5062,
    lon: 80.6480,
    currentTemp: 40,
    feelsLikeTemp: 46,
    humidity: 64,
    windSpeedKmH: 14,
    riskLevel: 'extreme',
    verdict: 'Very high heat and humidity. Stay hydrated and indoors.',
    isSafeOutsideNow: false,
    peakDangerWindow: '11:30 AM – 4:30 PM',
    uvIndex: 10,
    updatedAt: '7 mins ago',
  },
  {
    id: 'visakhapatnam',
    name: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    lat: 17.6868,
    lon: 83.2185,
    currentTemp: 36,
    feelsLikeTemp: 43,
    humidity: 76,
    windSpeedKmH: 18,
    riskLevel: 'danger',
    verdict: 'Warm coastal air with high thermal load. Seek shade.',
    isSafeOutsideNow: false,
    peakDangerWindow: '12:00 PM – 3:30 PM',
    uvIndex: 8,
    updatedAt: '14 mins ago',
  },
  {
    id: 'shimla',
    name: 'Shimla',
    state: 'Himachal Pradesh',
    lat: 31.1048,
    lon: 77.1734,
    currentTemp: 21,
    feelsLikeTemp: 21,
    humidity: 60,
    windSpeedKmH: 10,
    riskLevel: 'safe',
    verdict: 'Cool and very comfortable. Completely safe outdoors.',
    isSafeOutsideNow: true,
    peakDangerWindow: 'None',
    uvIndex: 4,
    updatedAt: '25 mins ago',
  },
];

export const HOURLY_MOCK_DATA: Record<string, HourlyForecastItem[]> = {
  delhi: [
    { time: '6 AM', hour: 6, temp: 28, feelsLike: 30, heatStressScore: 25, riskLevel: 'safe' },
    { time: '8 AM', hour: 8, temp: 31, feelsLike: 33, heatStressScore: 40, riskLevel: 'caution' },
    { time: '10 AM', hour: 10, temp: 35, feelsLike: 38, heatStressScore: 65, riskLevel: 'danger' },
    { time: '12 PM', hour: 12, temp: 39, feelsLike: 43, heatStressScore: 88, riskLevel: 'extreme' },
    { time: '2 PM', hour: 14, temp: 41, feelsLike: 45, heatStressScore: 95, riskLevel: 'extreme' },
    { time: '4 PM', hour: 16, temp: 40, feelsLike: 44, heatStressScore: 90, riskLevel: 'extreme' },
    { time: '6 PM', hour: 18, temp: 36, feelsLike: 38, heatStressScore: 60, riskLevel: 'danger' },
    { time: '8 PM', hour: 20, temp: 32, feelsLike: 34, heatStressScore: 45, riskLevel: 'caution' },
  ],
  ahmedabad: [
    { time: '6 AM', hour: 6, temp: 29, feelsLike: 31, heatStressScore: 30, riskLevel: 'safe' },
    { time: '8 AM', hour: 8, temp: 32, feelsLike: 34, heatStressScore: 45, riskLevel: 'caution' },
    { time: '10 AM', hour: 10, temp: 36, feelsLike: 39, heatStressScore: 70, riskLevel: 'danger' },
    { time: '12 PM', hour: 12, temp: 39, feelsLike: 42, heatStressScore: 85, riskLevel: 'extreme' },
    { time: '2 PM', hour: 14, temp: 40, feelsLike: 43, heatStressScore: 92, riskLevel: 'extreme' },
    { time: '4 PM', hour: 16, temp: 39, feelsLike: 42, heatStressScore: 84, riskLevel: 'extreme' },
    { time: '6 PM', hour: 18, temp: 35, feelsLike: 37, heatStressScore: 55, riskLevel: 'caution' },
    { time: '8 PM', hour: 20, temp: 32, feelsLike: 33, heatStressScore: 40, riskLevel: 'caution' },
  ],
  bengaluru: [
    { time: '6 AM', hour: 6, temp: 20, feelsLike: 20, heatStressScore: 10, riskLevel: 'safe' },
    { time: '8 AM', hour: 8, temp: 23, feelsLike: 23, heatStressScore: 15, riskLevel: 'safe' },
    { time: '10 AM', hour: 10, temp: 26, feelsLike: 27, heatStressScore: 25, riskLevel: 'safe' },
    { time: '12 PM', hour: 12, temp: 28, feelsLike: 29, heatStressScore: 30, riskLevel: 'safe' },
    { time: '2 PM', hour: 14, temp: 29, feelsLike: 30, heatStressScore: 32, riskLevel: 'safe' },
    { time: '4 PM', hour: 16, temp: 28, feelsLike: 29, heatStressScore: 30, riskLevel: 'safe' },
    { time: '6 PM', hour: 18, temp: 25, feelsLike: 25, heatStressScore: 20, riskLevel: 'safe' },
    { time: '8 PM', hour: 20, temp: 23, feelsLike: 23, heatStressScore: 15, riskLevel: 'safe' },
  ],
};

export const ADVISORIES_BY_PROFILE: Record<VulnerableProfile, AdvisoryItem[]> = {
  general: [
    {
      id: 'adv-g-1',
      title: 'Drink Clean Water Frequently',
      description: 'Sip water every 20-30 minutes, even if you do not feel thirsty. Avoid sugary or caffeinated drinks.',
      iconName: 'Droplets',
    },
    {
      id: 'adv-g-2',
      title: 'Stay in the Shade Between 11 AM - 4 PM',
      description: 'The sun emits peak thermal radiation during these hours. Postpone outdoor errands if possible.',
      iconName: 'Clock',
    },
    {
      id: 'adv-g-3',
      title: 'Wear Light-Colored, Loose Cotton',
      description: 'Cotton allows sweat evaporation. Use a wide-brim hat, umbrella, or cloth to cover your head.',
      iconName: 'Shirt',
    },
  ],
  elderly: [
    {
      id: 'adv-e-1',
      title: 'Keep Rooms Well-Ventilated or Cooled',
      description: 'Elderly bodies regulate temperature slower. Use fans, damp curtains, or cool foot-baths.',
      iconName: 'Home',
    },
    {
      id: 'adv-e-2',
      title: 'Check Blood Pressure & Medications',
      description: 'Certain heart and blood pressure medicines increase vulnerability to dehydration. Take as prescribed.',
      iconName: 'Heart',
    },
    {
      id: 'adv-e-3',
      title: 'Avoid Any Midday Steps Outdoors',
      description: 'Complete morning walks before 8:00 AM or evening strolls after 6:30 PM only.',
      iconName: 'Sun',
    },
  ],
  workers: [
    {
      id: 'adv-w-1',
      title: 'Take Mandatory 15-Minute Shade Breaks',
      description: 'Rest in full shade every hour of hard physical labor to let your internal body core cool down.',
      iconName: 'Clock',
    },
    {
      id: 'adv-w-2',
      title: 'Add Salt / ORS to Drinking Water',
      description: 'Excessive sweating depletes vital electrolytes. Drink ORS (Oral Rehydration Salts) or lemon water.',
      iconName: 'Droplets',
    },
    {
      id: 'adv-w-3',
      title: 'Buddy System for Warning Signs',
      description: 'Look out for colleagues: confusion, slurred speech, or stopping sweating are medical emergencies.',
      iconName: 'Heart',
    },
  ],
  children: [
    {
      id: 'adv-c-1',
      title: 'Never Leave Anyone in a Parked Vehicle',
      description: 'Vehicle interiors reach deadly 50°C+ temperatures in under 10 minutes, even with cracked windows.',
      iconName: 'Home',
    },
    {
      id: 'adv-c-2',
      title: 'Cancel Midday Outdoor Play',
      description: 'Children produce more heat relative to body mass. Keep sports and games indoors during hot hours.',
      iconName: 'Sun',
    },
    {
      id: 'adv-c-3',
      title: 'Offer Water Regularly',
      description: 'Children often forget to hydrate while active. Keep fresh water and fruits readily accessible.',
      iconName: 'Droplets',
    },
  ],
};
